# Core Colors
background            #060805
foreground            #d7f4c4
selection_foreground  #152b0c
selection_background  #b8d4a7
cursor                #b8d4a7
cursor_text_color     #152b0c

# Regular Colors
color0  #11140f
color1  #ebb2ff
color2  #a1c9ff
color3  #ffb4a4
color4  #a4d48c
color5  #72d6db
color6  #f3bf48
color7  #d7f4c4

# Bright Colors
color8  #152b0c
color9  #f8d8ff
color10 #d2e4ff
color11 #ffdad3
color12 #bff0a5
color13 #8ff2f7
color14 #ffdea0
color15 #b8d4a7
