# Core Colors
background            #04080d
foreground            #f7f9ff
selection_foreground  #001e30
selection_background  #82c8ff
cursor                #82c8ff
cursor_text_color     #001e30

# Regular Colors
color0  #0e161d
color1  #f9afe6
color2  #d1ca69
color3  #90cdff
color4  #d1ca69
color5  #4ddad7
color6  #ffb599
color7  #f7f9ff

# Bright Colors
color8  #03283f
color9  #ffd7f1
color10 #ede682
color11 #cbe6ff
color12 #ede682
color13 #6ff7f4
color14 #ffdbce
color15 #e3e9f0
