# Core Colors
background            #0b0608
foreground            #ffe4ed
selection_foreground  #3e1a2b
selection_background  #f6bcd3
cursor                #f6bcd3
cursor_text_color     #3e1a2b

# Regular Colors
color0  #181214
color1  #ffb77e
color2  #a6c8ff
color3  #95d879
color4  #f2b1ee
color5  #2bdcd9
color6  #ffb4a2
color7  #ffe4ed

# Bright Colors
color8  #3e1a2b
color9  #ffdcc3
color10 #d5e3ff
color11 #b0f593
color12 #ffd6f9
color13 #58f9f6
color14 #ffdad2
color15 #f6bcd3
